- name: ensure binary is present
  unarchive:
    src: "{{download_url}}"
    dest: "{{install_dir}}"
    remote_src: yes
  args:
    creates: "{{install_dir}}/{{name}}"

- name: ensure user exists
  user:
    name: "{{user}}"

- name: ensure needed directories exist
  file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{group}}"
    state: directory
  with_items:
    - "{{data_dir}}"
    - "{{config_dir}}"

- name: ensure eth0 ip is known
  setup:

- name: ensure configuration is in place
  template:
    src: "agent.json.j2"
    dest: "{{config_dir}}/agent.json"
    owner: "{{user}}"
    group: "{{group}}"

- name: ensure service has been installed
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{name}}.service

- name: ensure service has been enabled/is running
  systemd:
    name: "{{name}}"
    enabled: yes
    state: started
    daemon_reload: yes
