- name: ensure binary is present
  get_url:
    url: "{{download_url}}"
    dest: "{{install_dir}}/{{name}}"
    mode: 0755

- name: ensure user exists
  user:
    name: "{{user}}"

- name: ensure service has been installed
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{name}}.service

- name: ensure service has been enabled/is running
  systemd:
    name: "{{name}}"
    enabled: yes
    state: started
    daemon_reload: yes

- name: ensure requests to port 80 are redirected port 9999 (fabio)
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 9999

- name: ensure high availability packages are needed
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - jq
    - awscli

- name: ensure high availability watch script is in place
  template:
    src: ha-assign-public-ip.j2
    dest: "{{install_dir}}/ha-assign-public-ip"
    mode: 0755

- name: ensure consul watch is in place
  template:
    src: consul.json.j2
    dest: /etc/consul.d/fabio.json
    owner: consul
    group: consul

- name: ensure consul restarts
  systemd:
    name: consul
    state: restarted
