- name: ensure machine statistics are known
  setup:

# https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html
- name: ensure memory swapping is disabled
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

# https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
- name: ensure mmap limit is high enough
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: ensure package has been installed
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: ensure configuration is present
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml

- name: ensure elasticsearch.service.d folder is present
  file:
    path: /etc/systemd/system/elasticsearch.service.d
    state: directory

- name: ensure memory configuration is present
  template:
    src: elasticsearch.conf.j2
    dest: /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf


- name: ensure jvm configuration is present
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options

- name: ensure service has been enabled/is running
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
    daemon_reload: yes

- name: ensure service is registered with consul
  template:
    src: service.json.j2
    dest: /etc/consul.d/elasticsearch.json
