- name: ensure binary is present
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

- name: ensure needed directories exist
  file:
    dest: /etc/dnsmasq.d
    state: directory

- name: ensure .consul domains delegate to consul
  copy:
    content: |
      server=/consul./127.0.0.1#8600
      listen-address=127.0.0.1
      bind-interfaces
    dest: /etc/dnsmasq.d/consul

- name: ensure requests over eth0 are allowed
  copy:
    content: interface=eth0
    dest: /etc/dnsmasq.d/interface
  when: "{{listen_on_eth0 is defined}}"

- name: ensure service has been enabled/is running
  systemd:
    name: dnsmasq
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: ensure dnsmasq is used for resolving dns
  lineinfile:
    insertbefore: BOF
    state: present
    line: nameserver 127.0.0.1
    dest: /etc/resolvconf/resolv.conf.d/consul
    create: yes
