- name: ensure service is registered with consul
  template:
    src: service.json.j2
    dest: /etc/consul.d/vpn.json

- name: add keys to apt
  apt_key:
    id: "{{item}}"
    keyserver: hkp://keyserver.ubuntu.com
    state: present
  with_items:
   - 42F3E95A2C4F08279C4960ADD68FA50FEA312927
   - 7568D9BB55FF9E5287D586017AE645C0CF8E292A

- name: add ppas to apt
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    - deb http://repo.pritunl.com/stable/apt xenial main

- name: ensure apt packages are installed
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - pritunl
    - mongodb-org

- name: ensure service has been enabled/is running
  systemd:
    name: "{{item}}"
    enabled: yes
    state: started
  with_items:
    - pritunl
    - mongod

- name: ensure setup key is known
  shell: pritunl setup-key
  register: setup_key

- name: ensure pritunl has been initialized
  uri:
    url: https://{{inventory_hostname}}/setup/mongodb
    method: PUT
    validate_certs: no
    body_format: json
    body:
      setup_key: "{{setup_key.stdout}}"
      mongodb_uri: mongodb://localhost:27017/pritunl
