- name: ensure binary is present
  unarchive:
    src: "{{download_url}}"
    dest: "{{install_dir}}"
    remote_src: yes
  args:
    creates: "{{install_dir}}/{{name}}"

- name: ensure mlock syscall can be used without root access
  capabilities:
    capability: cap_ipc_lock=+ep
    path: "{{install_dir}}/{{name}}"

- name: ensure user exists
  user:
    name: "{{user}}"

- name: ensure needed directories exist
  file:
    path: "{{config_dir}}"
    state: directory

- name: ensure configuration is in place
  template:
    src: vault.hcl.j2
    dest: "{{config_dir}}/vault.hcl"

- name: ensure service has been installed
  template:
    src: systemd.service.j2
    dest: /etc/systemd/system/{{name}}.service

- name: ensure service has been enabled/is running
  systemd:
    name: "{{name}}"
    enabled: yes
    state: started
    daemon_reload: yes
