- hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  vars:
    hostnumber: "{{groups.all.index(inventory_hostname)}}"
  roles:
    - role: base
      tags: base
    - role: awscli
      tags: awscli
    - role: dnsmasq
      tags: dnsmasq
    - role: hostname
      tags: hostname
      hostname: management-cluster-{{hostnumber}}
    - role: consul
      tags: consul
      agent_mode: server
    - role: nomad
      tags: nomad
      agent_mode: server
    - role: vault
      tags: vault
    - role: fabio
      tags: fabio
