name: consul
version: 0.7.2
download_url: https://releases.hashicorp.com/{{name}}/{{version}}/{{name}}_{{version}}_linux_amd64.zip

user: "{{name}}"
group: "{{name}}"
install_dir: /usr/local/bin
data_dir: /mnt/{{name}}
config_dir: /etc/{{name}}.d

# consul_hosts is expected to be provided at command line via -e
cluster_size: "{{consul_hosts|length}}"
